server:
  port: 8084

spring:
  application:
    name: APIGATEWAY

  config:
    import=optional:configserver:http://config-server:8085
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa12crqnr3QU6bTN698
            client-secret: Z4Y8YHbVQzdlgEhSp7grCivXQ4drJ9aDDycE3thC_j7TTp1TJCauYk2u12IFIbLx
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          okta:
            issuer-uri: https://integrator-8250368.okta.com/oauth2/default

      resourceserver:
        jwt:
          issuer-uri: https://integrator-8250368.okta.com/oauth2/default
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka