server:
  port: 8081

spring:
  application:
    name: USERSERVICE

  datasource:
    url: jdbc:mysql://hotel-rating-db.cmfgoy2ca395.us-east-1.rds.amazonaws.com:3306/userdb
    username: admin
    password: viditmalik54321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
   import: optional:configserver:http://config-server:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-8250368.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://service-registry:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      userRateLimiter:
        limit-for-period: 1
        limit-refresh-period: 10s
        timeout-duration: 0s

  circuitbreaker:
    instances:
      User_Service_Rating_Breaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 6
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      ratingRetry:
        max-attempts: 3
        wait-duration:
          seconds: 3



