server:
  port: 8083

spring:
  application:
    name: RATINGSERVICE  
      ✅ (top level)
  datasource:
    url: jdbc:mysql://hotel-rating-db.cmfgoy2ca395.us-east-1.rds.amazonaws.com:3306/ratingdb?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: viditmalik54321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://config-server:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-8250368.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka